// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ModalController from "./modal_controller.civet"
application.register("modal", ModalController)

import NodeConfirmationController from "./node_confirmation_controller.civet"
application.register("node-confirmation", NodeConfirmationController)

import NodeNicController from "./node_nic_controller.civet"
application.register("node-nic", NodeNicController)
