require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'db/schema.rb'

# Loose Metrics
Metrics/AbcSize:
  Max: 23

Metrics/BlockLength:
  Max: 38

Metrics/BlockNesting:
  Max: 5

Metrics/ClassLength:
  Max: 150

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/MethodLength:
  Max: 15

Metrics/ModuleLength:
  Max: 150

Metrics/ParameterLists:
  Max: 8

Metrics/PerceivedComplexity:
  Max: 11

# for version 0.80

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

# Custom

Bundler/OrderedGems:
  Enabled: false

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Rails/FilePath:
  EnforcedStyle: arguments
