# https://docs.rubocop.org/rubycop/

require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'db/schema.rb'

Rails:
  Enabled: true

# Layout
Layout/ExtraSpacing:
  Exclude:
    - 'db/migrate/*.rb'

Layout/LineLength:
  Max: 120

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

# Loose Metrics
Metrics/AbcSize:
  Max: 23

Metrics/BlockLength:
  Max: 38

Metrics/BlockNesting:
  Max: 5

Metrics/ClassLength:
  Max: 150

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/MethodLength:
  Max: 15
  CountAsOne: ['array', 'hash', 'heredoc']
  Exclude:
    - 'db/migrate/*.rb'

Metrics/ModuleLength:
  Max: 150

Metrics/ParameterLists:
  Max: 8

Metrics/PerceivedComplexity:
  Max: 11

# Style
Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/WordArray:
  MinSize: 3

Style/NumericLiterals:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/SpecialGlobalVars:
  EnforcedStyle: use_perl_names

Style/AccessModifierDeclarations:
  EnforcedStyle: inline

Style/GuardClause:
  AllowConsecutiveConditionals: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

# Bundler
# https://docs.rubocop.org/rubocop/cops_bundler.html

Bundler/OrderedGems:
  Enabled: false

# Rails
# https://docs.rubocop.org/rubocop-rails/cops_rails.html

Rails/BulkChangeTable:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false
