# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Overwrite or add rules to create your own house style

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'db/schema.rb'
    - 'vender/**/*'

# Layout

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/ArrayAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/EndAlignment:
  EnforcedStyleAlignWith: start_of_line

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/ExtraSpacing:
  Exclude:
    - 'db/migrate/*.rb'

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/FirstMethodArgumentLineBreak:
  Enabled: false

Layout/FirstMethodParameterLineBreak:
  Enabled: false

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Layout/LineLength:
  Max: 80
  AllowedPatterns:
    - '^\s*#'

Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: same_line

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/SpaceInsideArrayLiteralBrackets:
  EnforcedStyle: no_space

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

# Metrics double

Metrics/AbcSize:
  Max: 34 # 17

Metrics/BlockLength:
  Max: 50 # 25
  AllowedMethods:
    - refine
    - module_eval
    - class_eval
  Exclude:
    - 'lib/tasks/*.rake'

Metrics/BlockNesting:
  Max: 6 # 3

Metrics/ClassLength:
  Max: 200 # 100
  Exclude:
    - 'test/**/*.rb'
    - 'app/controllers/*.rb'

Metrics/CyclomaticComplexity:
  Max: 14 # 7

Metrics/MethodLength:
  Max: 20 # 10
  CountAsOne: ['array', 'hash', 'heredoc']
  Exclude:
    - 'db/migrate/*.rb'

Metrics/ModuleLength:
  Max: 200 # 100

Metrics/ParameterLists:
  Max: 10 # 5
  MaxOptionalParameters: 6 # 3

Metrics/PerceivedComplexity:
  Max: 16 # 8

# Style

Style/AccessModifierDeclarations:
  EnforcedStyle: inline

Style/AsciiComments:
  Enabled: false

Style/BlockDelimiters:
  EnforcedStyle: line_count_based

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/FormatString:
  EnforcedStyle: percent

Style/FormatStringToken:
  MaxUnannotatedPlaceholdersAllowed: 3

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/GlobalStdStream:
  Enabled: false

Style/GuardClause:
  MinBodyLength: 2
  AllowConsecutiveConditionals: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/OneLineConditional:
  AlwaysCorrectToMultiline: true

Style/Lambda:
  EnforcedStyle: literal

Style/MultilineBlockChain:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/RedundantConstantBase:
  Enabled: false

Style/RedundantFetchBlock:
  Enabled: false

Style/RedundantLineContinuation:
  Enabled: false

Style/SpecialGlobalVars:
  EnforcedStyle: use_perl_names

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  EnforcedStyle: brackets

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: no_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/WordArray:
  MinSize: 6

# Bundler
# https://docs.rubocop.org/rubocop/cops_bundler.html

Bundler/OrderedGems:
  Enabled: false

# Rails
# https://docs.rubocop.org/rubocop-rails/cops_rails.html

Rails:
  Enabled: true

Rails/BulkChangeTable:
  Enabled: false

Rails/FilePath:
  EnforcedStyle: slashes

Rails/HasAndBelongsToMany:
  Enabled: false
