# https://docs.rubocop.org/rubycop/

require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'db/schema.rb'

Rails:
  Enabled: true

# Bundler
# https://docs.rubocop.org/rubocop/cops_bundler.html

Bundler/OrderedGems:
  Enabled: false

Layout/ExtraSpacing:
  Exclude:
    - 'db/migrate/*.rb'

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Layout/LineLength:
  Max: 80

Style/NumericLiterals:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

# Loose Metrics
Metrics/AbcSize:
  Max: 23

Metrics/BlockLength:
  Max: 38

Metrics/BlockNesting:
  Max: 5

Metrics/ClassLength:
  Max: 150

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/MethodLength:
  Max: 15
  CountAsOne: ['array', 'hash', 'heredoc']
  Exclude:
    - 'db/migrate/*.rb'

Metrics/ModuleLength:
  Max: 150

Metrics/ParameterLists:
  Max: 8

Metrics/PerceivedComplexity:
  Max: 11

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/WordArray:
  MinSize: 3

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/SpecialGlobalVars:
  EnforcedStyle: use_perl_names

# Rails
# https://docs.rubocop.org/rubocop-rails/cops_rails.html

Rails/BulkChangeTable:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false
