source "https://rubygems.org"
git_source(:github) do |repo|
  "https://github.com/#{repo}.git"
end

ruby ">= 3.3.0"

# Default gems generated by `rails new`
# database: mysql
# asset-pipeline: propshaft
# javascript: esbuild
# css: sass

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 7.2.1"
# The modern asset pipeline for Rails [https://github.com/rails/propshaft]
gem "propshaft"
# Use mysql as the database for Active Record
gem "mysql2", "~> 0.5"
# Use the Puma web server [https://github.com/puma/puma]
gem "puma", ">= 5.0"
# Bundle and transpile JavaScript [https://github.com/rails/jsbundling-rails]
gem "jsbundling-rails"
# Hotwire's SPA-like page accelerator [https://turbo.hotwired.dev]
gem "turbo-rails"
# Hotwire's modest JavaScript framework [https://stimulus.hotwired.dev]
gem "stimulus-rails"
# Bundle and process CSS [https://github.com/rails/cssbundling-rails]
gem "cssbundling-rails"
# Build JSON APIs with ease [https://github.com/rails/jbuilder]
gem "jbuilder"
# Use Redis adapter to run Action Cable in production
gem "redis", ">= 4.0.1"

# Use Kredis to get higher-level data types in Redis [https://github.com/rails/kredis]
# gem "kredis"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem "bcrypt", "~> 3.1.7"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: [:windows, :jruby]

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "image_processing", "~> 1.2"

## Other gems

# Use Slim for HTML
gem "slim-rails"

# Config
gem "config"

# i18n
gem "rails-i18n", "~> 7.0"

# Devise
gem "devise"
gem "devise-i18n"
gem "devise_ldap_authenticatable"

# Pundit
gem "pundit"

# Paper Trail
gem "paper_trail"
gem "paper_trail-association_tracking"

# Rails Admin
gem "rails_admin", "~> 3.2"
gem "rails_admin-i18n"

# Bootstrap
gem "bootstrap_form", "~> 5.4"

# Resque
gem "resque"
gem "resque-scheduler"

# Ransack
gem "ransack"

# Whenever
gem "whenever", require: false

# Color
gem "color"

# TODO: remove when redis_cache_store supports connection_pool 3+ (Rails 8.1.2+)
gem "connection_pool", "< 3.0"

## Bundled gems
gem "csv"

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: [:mri, :windows], require: "debug/prelude"

  # Static analysis for security vulnerabilities [https://brakemanscanner.org/]
  gem "brakeman", require: false

  # Omakase Ruby styling [https://github.com/rails/rubocop-rails-omakase/]
  gem "rubocop-rails-omakase", require: false
end

group :development do
  # Use console on exceptions pages [https://github.com/rails/web-console]
  gem "web-console"

  ## Other gems
  gem "ruby-lsp", require: false
  gem "ruby-lsp-rails", require: false
  gem "slim_lint"
end

group :test do
  # Use system testing [https://guides.rubyonrails.org/testing.html#system-testing]
  gem "capybara"
  gem "selenium-webdriver"

  ## Other gems
  gem "minitest-stub-const"

  # TODO: remove when minitest rails supports Minitest 6+
  # https://github.com/minitest/minitest/issues/1045
  gem "minitest", "< 6.0"
end
